
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhis
 */
public class SignUp extends javax.swing.JFrame {

    
    
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        AddUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        phoneNumber1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Mobilevalidation = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        passworderror = new javax.swing.JLabel();
        Otparea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        OtpCheck = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Sendotp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.SystemColor.control);
        jPanel2.setOpaque(false);

        AddUser.setBackground(new java.awt.Color(204, 204, 204));
        AddUser.setText("Add New User");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login ");

        phoneNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumber1ActionPerformed(evt);
            }
        });
        phoneNumber1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumber1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneNumber1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumber1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Phone Number ");

        Mobilevalidation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mobilevalidation.setForeground(new java.awt.Color(204, 0, 0));
        Mobilevalidation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        passworderror.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passworderror.setForeground(new java.awt.Color(204, 0, 51));

        Otparea.setToolTipText("");
        Otparea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtpareaActionPerformed(evt);
            }
        });
        Otparea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OtpareaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OtpareaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OtpareaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Enter otp");

        OtpCheck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OtpCheck.setForeground(new java.awt.Color(255, 0, 51));
        OtpCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Login.setBackground(new java.awt.Color(204, 204, 204));
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(204, 204, 204));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Sendotp.setBackground(new java.awt.Color(204, 204, 204));
        Sendotp.setText("Send Otp");
        Sendotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendotpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 219, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(phoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Mobilevalidation, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passworderror, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Otparea, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OtpCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddUser)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(Sendotp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Login)
                .addGap(116, 116, 116)
                .addComponent(Reset)
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(AddUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumber1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mobilevalidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passworderror, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Otparea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Login)
                            .addComponent(Reset)
                            .addComponent(Sendotp))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(OtpCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 730, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhis\\OneDrive\\Desktop\\Guessing_Game\\src\\icons\\game-bg.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1200, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumber1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_phoneNumber1ActionPerformed
   
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        verification( Phoneno, Password,value);
    }//GEN-LAST:event_LoginActionPerformed
   
    private void OtpareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtpareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtpareaActionPerformed
     
    
    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        // TODO add your handling code here:
        close();
        NewUser newUser = new NewUser();
        newUser.setVisible(true);
    }//GEN-LAST:event_AddUserActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_ResetActionPerformed

    private void SendotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendotpActionPerformed
        // TODO add your handling code here:
        validation1();
    }//GEN-LAST:event_SendotpActionPerformed

    private void phoneNumber1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumber1KeyPressed
        // TODO add your handling code here:
        PhonenumberCheck();
    }//GEN-LAST:event_phoneNumber1KeyPressed

    private void phoneNumber1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumber1KeyReleased
        // TODO add your handling code here:
        PhonenumberCheck();
    }//GEN-LAST:event_phoneNumber1KeyReleased

    private void OtpareaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OtpareaKeyPressed
        // TODO add your handling code here:
        OtpCheck();
    }//GEN-LAST:event_OtpareaKeyPressed

    private void OtpareaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OtpareaKeyReleased
        // TODO add your handling code here:
        OtpCheck();
    }//GEN-LAST:event_OtpareaKeyReleased

    private void OtpareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OtpareaKeyTyped
        // TODO add your handling code here:
        OtpCheck();
    }//GEN-LAST:event_OtpareaKeyTyped

    private void phoneNumber1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumber1KeyTyped
        // TODO add your handling code here:
        PhonenumberCheck();
    }//GEN-LAST:event_phoneNumber1KeyTyped

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        Passwordcheck();
        
    }//GEN-LAST:event_passwordKeyPressed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        Passwordcheck();
    }//GEN-LAST:event_passwordKeyReleased

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        Passwordcheck();
    }//GEN-LAST:event_passwordKeyTyped
      String Phoneno,Password,otp;
       boolean validation(){
           Phoneno=phoneNumber1.getText();
           Password = password.getText();
           otp =Otparea.getText();
           if(Phoneno.equals("")){
               JOptionPane.showMessageDialog(this,"Please Enter mobile number");
               return false;
           }
           if(Password.equals("")){
               JOptionPane.showMessageDialog(this,"Please Enter Password");
               return false;
           }
            if(otp.equals("")){
               JOptionPane.showMessageDialog(this,"Please Enter One Time Password");
               return false;
           } else{
               
              
           }
         
             
       return true;
       } 
    
    
    boolean validation1(){
           Phoneno=phoneNumber1.getText();
           Password =password.getText();
           if(Phoneno.equals("")){
               JOptionPane.showMessageDialog(this,"Please enter mobile number");
               return false;
           } 
           
           Messagesend(value);
       return true;
       }
    
    
    
    
    void PhonenumberCheck(){
        Phoneno=phoneNumber1.getText();
        if(Phoneno.length() == 10){
            Mobilevalidation.setText("");
        }else{
             Mobilevalidation.setText("Enter 10 Digit Mobile Number ");
        }
    
    }
     void Passwordcheck() {
    if (password.getText().length() < 8) {
        passworderror.setText("Please enter  8 characters password");
    } else {
        passworderror.setText("");
    }
}
        public static String optgenrator() {
        int length;
        int otp = 0;
        String otps = "";
        length = 4;
        for (int i = 0; i < length; i++){
            otp = (int) (Math.floor(Math.random() * 10));
            otps += Integer.toString(otp);
        }
        return otps;
    }
        public String value = optgenrator();
   
        void Messagesend( String otp) {
            Phoneno=phoneNumber1.getText();
        try {
            String apikey = "MYgsaEg1VPcfpStV2RCelQiEBaexBE1r3gD5fPFFi4BjcobUN39smbbD44tC";
            String route = "otp";
            String url = "https://www.fast2sms.com/dev/bulkV2?authorization=" + apikey + "&variables_values=" + otp + "&route=" + route + "&numbers=" + Phoneno;

            // Get request
            URL myurl = new URL(url);
            HttpsURLConnection connection = (HttpsURLConnection) myurl.openConnection();
            connection.setRequestMethod("GET"); // setting method
            connection.setRequestProperty("User-Agent", "Mozilla/5.0"); // set properties
            connection.setRequestProperty("cache-control", "no-cache"); // set properties
            System.out.println("Wait....");
            int responsecode = connection.getResponseCode();
            System.out.println("Response code is " + responsecode);
            StringBuffer responsereader = new StringBuffer();
            BufferedReader br = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String line;
            while ((line = br.readLine()) != null) {
                responsereader.append(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    void verification(String Phoneno,String Password,String otp){
       
        if(validation()){
    try{
            String url="jdbc:mysql://localhost:3306/guessinggamedatabase?zeroDateTimeBehavior=CONVERT_TO_NULL";
            String user="root";
            String password1="1808";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url,user,password1);
            String sql ="select * from signup where ContactNumber=? and Password=?";
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1,Phoneno);
            st.setString(2, Password);
            ResultSet rs =st.executeQuery();
            String otp1=Otparea.getText();
            if(value.equals(otp1)){
           while(rs.next()){
            FinalPage fp = new FinalPage();
            fp.setVisible(true);
            this.dispose();
           }
         } else{
                  JOptionPane.showMessageDialog(this,"Incorrect Otp " );
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Incorrect Phone Number or Password");
        }   
    }}
    
    void OtpCheck(){
          String Otparea1 =Otparea.getText();
        if(Otparea1.length()==4){
              OtpCheck.setText("");
        }else{
             OtpCheck.setText("Enter 4 Digit Otp Number");
        }
    
    }
        public void close(){
            WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
            
        }
        
        
        public void clear(){
             phoneNumber1.setText("");
             Mobilevalidation.setText("");
             passworderror.setText("");
             OtpCheck.setText("");
             Otparea.setText("");
             password.setText("");
             
            
            
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
           
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUser;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Mobilevalidation;
    private javax.swing.JLabel OtpCheck;
    private javax.swing.JTextField Otparea;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Sendotp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passworderror;
    private javax.swing.JTextField phoneNumber1;
    // End of variables declaration//GEN-END:variables
}
